name: Docker CI-CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: docker build -t prayags/gitlab-ci-demo:latest .

      # Push Docker image
      - name: Push Docker image
        run: docker push prayags/gitlab-ci-demo:latest

      # Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}       # EC2 public IP
          username: ${{ secrets.EC2_USER }}   # usually 'ubuntu'
          key: ${{ secrets.EC2_SSH_KEY }}     # private key stored as secret
          script: |
            # Stop & remove existing container if exists
            docker stop gitlab-ci-demo || true
            docker rm gitlab-ci-demo || true

            # Cleanup unused Docker resources
            docker system prune -af
            docker volume prune -f

            # Pull latest image
            docker pull prayags/gitlab-ci-demo:latest

            # Run container
            docker run -d -p 80:80 --name gitlab-ci-demo prayags/gitlab-ci-demo:latest
